@isTest
private class Fin_InvoiceExtControllerTests {

    // testMethod static void testSubmit() {
    //     FIN_Invoice__c invoice= new FIN_Invoice__c();
    //     insert invoice;
        
    //     Test.startTest();
    //     Fin_InvoiceExtController con = new Fin_InvoiceExtController(new ApexPages.StandardController(invoice));
    //     con.onSubmit();
    //     invoice= [SELECT ApprovalStatus__c FROM FIN_Invoice__c WHERE Id = :invoice.Id LIMIT 1];
    //     Test.stopTest();
        
    //     System.assertEquals('Approved', invoice.ApprovalStatus__c );
    // }
    
    // testMethod static void testRecall() {
    //     FIN_Invoice__c invoice= new FIN_Invoice__c();
    //     insert invoice;
        
    //     Test.startTest();
    //     Fin_InvoiceExtController con = new Fin_InvoiceExtController (new ApexPages.StandardController(invoice));
    //     con.onRecall();
    //     invoice= [SELECT ApprovalStatus__c  FROM FIN_Invoice__c WHERE Id = :invoice.Id LIMIT 1];
    //     Test.stopTest();
        
    //     System.assertEquals('Recalled', invoice.ApprovalStatus__c );
    // }
}